name: guardar_datos

on:
  push:
    branches:
      - main

jobs:
  guardar_datos_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Ejecutar script para guardar datos
        run: |
          # Aquí va el script que guarda los datos en el repositorio
          # Usa el token de acceso personal para autenticarte
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Guardar datos"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
