name: guardar_datos

on:
  push:
    branches:
      - main

jobs:
  guardar_datos_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Ejecutar script para guardar datos
        run: |
          echo "Guardando datos en el archivo..."
          echo "Nuevos datos" >> datos.txt
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add datos.txt
          git commit -m "Actualizar datos"
          git push
